/*
 * This program is the LINGERING ALIENS MAKE EARTH ATTACK!(LAME)
 * The game is intended for fun and the author takes no blame for damage to your
 * hardware or emotional well being.
 * @author Eduardo Nava
 * @version 1.0
 */
 //include directives
#include "game_engine.h"
#include "screenAliens.h"

 
//hardware init
Timer timer;
SDFileSystem sd(p5, p6, p7, p8, "sd");
uLCD_4DGL uLCD(p28, p27, p29);
PinDetect pbLeft(p18);
PinDetect pbCenter(p17);
PinDetect pbRight(p16);
Speaker mySpeaker(p21);
Serial pc(USBTX,USBRX);
 
//---------------------------------------------------------------------------------------------------
// Callback routine is interrupt activated by a debounced pbLeft hit
// That is ... this code runs with interrupt is generated by first button press
void pb1_hit_callback (void)
{ 
  ASSERT_LEFT = 1;
}
//---------------------------------------------------------------------------------------------------
// Callback routine is interrupt activated by a debounced pbRight hit
// That is ... this code runs with interrupt is generated by second button press
void pb2_hit_callback (void) {
  ASSERT_RIGHT = 1; 
}
//---------------------------------------------------------------------------------------------------
// Callback routine is interrupt activated by a debounced pbCenter hit
// That is ... this code runs with interrupt is generated by third button press
void pb3_hit_callback (void)
{ 
  ASSERT_SHOOT = 1;
}
//--------------------------------------------------------------------------------------------------- 
 
int main(){
  uLCD.printf("\t\tLAME");
  //Setbaudrate

  //setup push buttons
  pbLeft.mode(PullUp); pbRight.mode(PullUp); pbCenter.mode(PullUp);
  // Delay for initial pullup to take effect 
  wait(.01);
  screenAlien** list = new screenAlien *[6];
  MMA8452 acc(p9, p10, 40000);  //instantiate an acc object!
 
   
  //set parameters -- use these and don't change
  acc.setBitDepth(MMA8452::BIT_DEPTH_12);
  acc.setDynamicRange(MMA8452::DYNAMIC_RANGE_4G);
  acc.setDataRate(MMA8452::RATE_100);
  wait(.01);
  // Setup Interrupt callback functions for a pb hit 
  pbLeft.attach_deasserted(&pb1_hit_callback); 
  pbRight.attach_deasserted(&pb2_hit_callback); 
  pbCenter.attach_deasserted(&pb3_hit_callback);
  // Start sampling pb inputs using interrupts 
  pbLeft.setSampleFrequency(); 
  pbRight.setSampleFrequency(); 
  pbCenter.setSampleFrequency();
  uLCD.printf("\nGameSetup");
  launch_game(list);
  double x;
  acc.readXGravity(&x);//NUMBER FROM 0 TO 1;
  wait(3);
  screenAlien::setFallTime(x);
  
  time_t startTime;
  startTime = time(0);
  
  //START game loop
  uLCD.cls();
  run_game(list);
  uLCD.cls();
  time_t endTime = time(0)-startTime;
  uLCD.printf("\n\n Congratulations!!\n\n Earth Saved!\n\n\n(%d Seconds)",endTime);
  
  
}
 